name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env:
      SKIP_PREFLIGHT_CHECK: true
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PORT: 3001
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install all
        run: npm run install:all
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3001
      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: afternoon-savannah-62909
          heroku_email: joonas@autua.fi
          healthcheck: https://afternoon-savannah-62909.herokuapp.com/health
          checkstring: ok
          rollbackonhealthcheckfailed: true
      - name: bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
